name: "medusa-action"

description: "Run Medusa, the smart contract fuzzer"

branding:
  icon: 'shield'  
  color: 'red'

inputs:
  timeout:
    description: "Time to run the campaign"
    required: false
  output-file:
    description: "Capture medusa's output into this file. The path must be relative to the repository root."
    required: false
  negate-exit-status:
    description: "Apply logical NOT to medusa-test's exit status (for testing the action)"
    required: false
  medusa-workdir:
    description: "Path to run medusa-test from."
    required: false
  internal-github-workspace:
    # Do not set manually. This is a hacky way to pass the host workspace to inside the action
    # This is used to improve compatibility when using ignore-compile.
    # GitHub rewrites the argument if it is passed directly, to we use toJSON to "transform"
    # it and avoid the remapping done by GitHub Actions.
    default: ${{ toJSON(github.workspace) }}

outputs:
  output-file:
    description: "If produced, the file containing medusa-test's output, relative to the repository root."
    value: ${{ steps.medusa.outputs.output-file }}

runs:
  using: "composite"
  steps:
    - run: |
        docker build -t eth-security-toolbox:latest ${{ github.action_path }}
      shell: bash
    - id: medusa
      run: |
        # medusa campaign
        ${{ github.action_path }}/launch.sh eth-security-toolbox:latest
      shell: bash
      env:
        INPUT_NEGATE-EXIT-STATUS: ${{ inputs.negate-exit-status }}
        INPUT_MEDUSA-WORKDIR: ${{ inputs.medusa-workdir }}
        INPUT_OUTPUT-FILE: ${{ inputs.output-file }}
        INPUT_INTERNAL-GITHUB-WORKSPACE: ${{ inputs.internal-github-workspace }}
